<?php
/**
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this extension to newer
 * version in the future.
 *
 * @category    Camoo
 * @package     Camoo_Enkap
 */

namespace Camoo\Enkap\Observer;

require_once __DIR__ . '/../vendor/autoload.php';

use \Magento\Framework\App\RequestInterface;
use \Enkap\OAuth\Services\CallbackUrlService;
use \Enkap\OAuth\Model\CallbackUrl;

class ConfigObserver implements \Magento\Framework\Event\ObserverInterface
{
    private $request;

    public function __construct(RequestInterface $request) 
    {
        $this->request = $request;
    }

    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        $params = $this->request->getParam('groups');
        $key = $params['custompayment']['fields']['public']['value'];
        $secret = $params['custompayment']['fields']['private']['value'];
        $sandbox = $params['custompayment']['fields']['sandbox']['value'];

        if($key && $secret){

            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

            $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
            $store = $storeManager->getStore();
            $baseUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);

            $setup = new CallbackUrlService($key, $secret, [], !$sandbox ? false : true);
            $callBack = $setup->loadModel(CallbackUrl::class);
            # The URL where to redirect the user after the payment is completed. It will contain the reference id generated by your system which was provided in the initial order placement request. E-nkap will append your reference id in the path of the URL with the form: http://localhost/action/return/{yourReferenceId}
            $callBack->return_url = $baseUrl.'enkap/success/index';
            
            # The URL used by E-nkap to instantly notify you about the status of the payment. E-nkap would append your reference Id (generated by your system and provided in the initial order placement request) as path variable and send a PUT with the status of the payment in the body as {"status":"[txStatus]"}, where [txStatus] the payment status.
            $callBack->notification_url = $baseUrl.'enkap/notify/index'; // this action should accept PUT Request
            $setup->set($callBack); 
        }
        return $this;
    }
}
